//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v15.3.0+131c9cd
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "gridLayoutItemProperties"
	/// <summary>Grid Layout Item Properties</summary>
	public partial interface IGridLayoutItemProperties : IPublishedElement
	{
		/// <summary>Align Items</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string GridItemAlignItems { get; }

		/// <summary>Justify Content</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string GridItemJustifyContent { get; }

		/// <summary>Margin Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int GridItemMarginBottom { get; }

		/// <summary>Margin Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int GridItemMarginLeft { get; }

		/// <summary>Margin Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int GridItemMarginRight { get; }

		/// <summary>Margin Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int GridItemMarginTop { get; }

		/// <summary>Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int GridItemPaddingBottom { get; }

		/// <summary>Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int GridItemPaddingLeft { get; }

		/// <summary>Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int GridItemPaddingRight { get; }

		/// <summary>Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int GridItemPaddingTop { get; }
	}

	/// <summary>Grid Layout Item Properties</summary>
	[PublishedModel("gridLayoutItemProperties")]
	public partial class GridLayoutItemProperties : PublishedElementModel, IGridLayoutItemProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const string ModelTypeAlias = "gridLayoutItemProperties";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<GridLayoutItemProperties, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public GridLayoutItemProperties(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Align Items
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gridItemAlignItems")]
		public virtual string GridItemAlignItems => GetGridItemAlignItems(this, _publishedValueFallback);

		/// <summary>Static getter for Align Items</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetGridItemAlignItems(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "gridItemAlignItems");

		///<summary>
		/// Justify Content
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("gridItemJustifyContent")]
		public virtual string GridItemJustifyContent => GetGridItemJustifyContent(this, _publishedValueFallback);

		/// <summary>Static getter for Justify Content</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetGridItemJustifyContent(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "gridItemJustifyContent");

		///<summary>
		/// Margin Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("gridItemMarginBottom")]
		public virtual int GridItemMarginBottom => GetGridItemMarginBottom(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetGridItemMarginBottom(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "gridItemMarginBottom");

		///<summary>
		/// Margin Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("gridItemMarginLeft")]
		public virtual int GridItemMarginLeft => GetGridItemMarginLeft(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetGridItemMarginLeft(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "gridItemMarginLeft");

		///<summary>
		/// Margin Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("gridItemMarginRight")]
		public virtual int GridItemMarginRight => GetGridItemMarginRight(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetGridItemMarginRight(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "gridItemMarginRight");

		///<summary>
		/// Margin Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("gridItemMarginTop")]
		public virtual int GridItemMarginTop => GetGridItemMarginTop(this, _publishedValueFallback);

		/// <summary>Static getter for Margin Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetGridItemMarginTop(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "gridItemMarginTop");

		///<summary>
		/// Padding Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("gridItemPaddingBottom")]
		public virtual int GridItemPaddingBottom => GetGridItemPaddingBottom(this, _publishedValueFallback);

		/// <summary>Static getter for Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetGridItemPaddingBottom(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "gridItemPaddingBottom");

		///<summary>
		/// Padding Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("gridItemPaddingLeft")]
		public virtual int GridItemPaddingLeft => GetGridItemPaddingLeft(this, _publishedValueFallback);

		/// <summary>Static getter for Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetGridItemPaddingLeft(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "gridItemPaddingLeft");

		///<summary>
		/// Padding Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("gridItemPaddingRight")]
		public virtual int GridItemPaddingRight => GetGridItemPaddingRight(this, _publishedValueFallback);

		/// <summary>Static getter for Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetGridItemPaddingRight(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "gridItemPaddingRight");

		///<summary>
		/// Padding Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("gridItemPaddingTop")]
		public virtual int GridItemPaddingTop => GetGridItemPaddingTop(this, _publishedValueFallback);

		/// <summary>Static getter for Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetGridItemPaddingTop(IGridLayoutItemProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "gridItemPaddingTop");
	}
}
