//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v15.3.0+131c9cd
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Layout 1x1 Settings</summary>
	[PublishedModel("layout1X1Settings")]
	public partial class Layout1X1Settings : PublishedElementModel, IBackgroundImageProperties, ILayoutProperties, IOverlayProperties, IThemeProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const string ModelTypeAlias = "layout1X1Settings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<Layout1X1Settings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public Layout1X1Settings(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Background Image
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("backgroundImage")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops BackgroundImage => global::Umbraco.Cms.Web.Common.PublishedModels.BackgroundImageProperties.GetBackgroundImage(this, _publishedValueFallback);

		///<summary>
		/// Layout Margin Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutMarginBottom")]
		public virtual int LayoutMarginBottom => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutProperties.GetLayoutMarginBottom(this, _publishedValueFallback);

		///<summary>
		/// Layout Margin Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutMarginLeft")]
		public virtual int LayoutMarginLeft => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutProperties.GetLayoutMarginLeft(this, _publishedValueFallback);

		///<summary>
		/// Layout Margin Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutMarginRight")]
		public virtual int LayoutMarginRight => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutProperties.GetLayoutMarginRight(this, _publishedValueFallback);

		///<summary>
		/// Layout Margin Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutMarginTop")]
		public virtual int LayoutMarginTop => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutProperties.GetLayoutMarginTop(this, _publishedValueFallback);

		///<summary>
		/// Layout Padding Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutPaddingBottom")]
		public virtual int LayoutPaddingBottom => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutProperties.GetLayoutPaddingBottom(this, _publishedValueFallback);

		///<summary>
		/// Layout Padding Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutPaddingLeft")]
		public virtual int LayoutPaddingLeft => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutProperties.GetLayoutPaddingLeft(this, _publishedValueFallback);

		///<summary>
		/// Layout Padding Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutPaddingRight")]
		public virtual int LayoutPaddingRight => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutProperties.GetLayoutPaddingRight(this, _publishedValueFallback);

		///<summary>
		/// Layout Padding Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutPaddingTop")]
		public virtual int LayoutPaddingTop => global::Umbraco.Cms.Web.Common.PublishedModels.LayoutProperties.GetLayoutPaddingTop(this, _publishedValueFallback);

		///<summary>
		/// Overlay Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("overlayBackgroundColor")]
		public virtual string OverlayBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.OverlayProperties.GetOverlayBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Accent Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("darkModeAccentColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor DarkModeAccentColor => global::Umbraco.Cms.Web.Common.PublishedModels.ThemeProperties.GetDarkModeAccentColor(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("darkModeBackgroundColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor DarkModeBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.ThemeProperties.GetDarkModeBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("darkModeTextColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor DarkModeTextColor => global::Umbraco.Cms.Web.Common.PublishedModels.ThemeProperties.GetDarkModeTextColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Accent Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("lightModeAccentColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor LightModeAccentColor => global::Umbraco.Cms.Web.Common.PublishedModels.ThemeProperties.GetLightModeAccentColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("lightModeBackgroundColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor LightModeBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.ThemeProperties.GetLightModeBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("lightModeTextColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor LightModeTextColor => global::Umbraco.Cms.Web.Common.PublishedModels.ThemeProperties.GetLightModeTextColor(this, _publishedValueFallback);
	}
}
