//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v15.3.0+131c9cd
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "layoutProperties"
	/// <summary>Layout Properties</summary>
	public partial interface ILayoutProperties : IPublishedElement
	{
		/// <summary>Layout Margin Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int LayoutMarginBottom { get; }

		/// <summary>Layout Margin Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int LayoutMarginLeft { get; }

		/// <summary>Layout Margin Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int LayoutMarginRight { get; }

		/// <summary>Layout Margin Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int LayoutMarginTop { get; }

		/// <summary>Layout Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int LayoutPaddingBottom { get; }

		/// <summary>Layout Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int LayoutPaddingLeft { get; }

		/// <summary>Layout Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int LayoutPaddingRight { get; }

		/// <summary>Layout Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		int LayoutPaddingTop { get; }
	}

	/// <summary>Layout Properties</summary>
	[PublishedModel("layoutProperties")]
	public partial class LayoutProperties : PublishedElementModel, ILayoutProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const string ModelTypeAlias = "layoutProperties";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<LayoutProperties, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public LayoutProperties(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Layout Margin Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutMarginBottom")]
		public virtual int LayoutMarginBottom => GetLayoutMarginBottom(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Margin Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetLayoutMarginBottom(ILayoutProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "layoutMarginBottom");

		///<summary>
		/// Layout Margin Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutMarginLeft")]
		public virtual int LayoutMarginLeft => GetLayoutMarginLeft(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Margin Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetLayoutMarginLeft(ILayoutProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "layoutMarginLeft");

		///<summary>
		/// Layout Margin Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutMarginRight")]
		public virtual int LayoutMarginRight => GetLayoutMarginRight(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Margin Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetLayoutMarginRight(ILayoutProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "layoutMarginRight");

		///<summary>
		/// Layout Margin Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutMarginTop")]
		public virtual int LayoutMarginTop => GetLayoutMarginTop(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Margin Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetLayoutMarginTop(ILayoutProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "layoutMarginTop");

		///<summary>
		/// Layout Padding Bottom
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutPaddingBottom")]
		public virtual int LayoutPaddingBottom => GetLayoutPaddingBottom(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Padding Bottom</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetLayoutPaddingBottom(ILayoutProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "layoutPaddingBottom");

		///<summary>
		/// Layout Padding Left
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutPaddingLeft")]
		public virtual int LayoutPaddingLeft => GetLayoutPaddingLeft(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Padding Left</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetLayoutPaddingLeft(ILayoutProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "layoutPaddingLeft");

		///<summary>
		/// Layout Padding Right
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutPaddingRight")]
		public virtual int LayoutPaddingRight => GetLayoutPaddingRight(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Padding Right</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetLayoutPaddingRight(ILayoutProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "layoutPaddingRight");

		///<summary>
		/// Layout Padding Top
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("layoutPaddingTop")]
		public virtual int LayoutPaddingTop => GetLayoutPaddingTop(this, _publishedValueFallback);

		/// <summary>Static getter for Layout Padding Top</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static int GetLayoutPaddingTop(ILayoutProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<int>(publishedValueFallback, "layoutPaddingTop");
	}
}
