//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v15.3.0+131c9cd
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	/// <summary>Site Settings</summary>
	[PublishedModel("siteSettings")]
	public partial class SiteSettings : PublishedContentModel, INavigationProperties, ISiteProperties, ITwThemeProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const string ModelTypeAlias = "siteSettings";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<SiteSettings, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public SiteSettings(IPublishedContent content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Hide From Navigation
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("umbracoNaviHide")]
		public virtual bool UmbracoNaviHide => global::Umbraco.Cms.Web.Common.PublishedModels.NavigationProperties.GetUmbracoNaviHide(this, _publishedValueFallback);

		///<summary>
		/// Meta Description
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("metaDescription")]
		public virtual string MetaDescription => global::Umbraco.Cms.Web.Common.PublishedModels.SiteProperties.GetMetaDescription(this, _publishedValueFallback);

		///<summary>
		/// Redirect Type
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("redirectType")]
		public virtual string RedirectType => global::Umbraco.Cms.Web.Common.PublishedModels.SiteProperties.GetRedirectType(this, _publishedValueFallback);

		///<summary>
		/// Redirect URL
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("redirectUrl")]
		public virtual global::Umbraco.Cms.Core.Models.Link RedirectUrl => global::Umbraco.Cms.Web.Common.PublishedModels.SiteProperties.GetRedirectUrl(this, _publishedValueFallback);

		///<summary>
		/// Site Logo
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteLogo")]
		public virtual global::Umbraco.Cms.Core.Models.MediaWithCrops SiteLogo => global::Umbraco.Cms.Web.Common.PublishedModels.SiteProperties.GetSiteLogo(this, _publishedValueFallback);

		///<summary>
		/// Site Name
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("siteName")]
		public virtual string SiteName => global::Umbraco.Cms.Web.Common.PublishedModels.SiteProperties.GetSiteName(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Accent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("darkModeAccent")]
		public virtual bool DarkModeAccent => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetDarkModeAccent(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Background
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("darkModeBackground")]
		public virtual bool DarkModeBackground => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetDarkModeBackground(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("darkModeText")]
		public virtual bool DarkModeText => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetDarkModeText(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Accent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("lightModeAccent")]
		public virtual bool LightModeAccent => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetLightModeAccent(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Background
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("lightModeBackground")]
		public virtual bool LightModeBackground => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetLightModeBackground(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("lightModeText")]
		public virtual bool LightModeText => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetLightModeText(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Custom Accent Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModeCustomAccentColor")]
		public virtual string TwDarkModeCustomAccentColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwDarkModeCustomAccentColor(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Custom Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModeCustomBackgroundColor")]
		public virtual string TwDarkModeCustomBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwDarkModeCustomBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Custom Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModeCustomTextColor")]
		public virtual string TwDarkModeCustomTextColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwDarkModeCustomTextColor(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Preset Accent Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModePresetAccentColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetAccentColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwDarkModePresetAccentColor(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Preset Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModePresetBackgroundColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwDarkModePresetBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Dark Mode Preset Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModePresetTextColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetTextColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwDarkModePresetTextColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Custom Accent Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModeCustomAccentColor")]
		public virtual string TwLightModeCustomAccentColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwLightModeCustomAccentColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Custom Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModeCustomBackgroundColor")]
		public virtual string TwLightModeCustomBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwLightModeCustomBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Custom Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModeCustomTextColor")]
		public virtual string TwLightModeCustomTextColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwLightModeCustomTextColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Preset Accent Color: Select the accent color from predefined colors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModePresetAccentColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetAccentColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwLightModePresetAccentColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Preset Background Color: Select the background color from predefined colors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModePresetBackgroundColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetBackgroundColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwLightModePresetBackgroundColor(this, _publishedValueFallback);

		///<summary>
		/// Light Mode Preset Text Color: Select the text color from predefined colors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModePresetTextColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetTextColor => global::Umbraco.Cms.Web.Common.PublishedModels.TwThemeProperties.GetTwLightModePresetTextColor(this, _publishedValueFallback);
	}
}
