//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder.Embedded v15.3.0+131c9cd
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Linq.Expressions;
using Umbraco.Cms.Core.Models.PublishedContent;
using Umbraco.Cms.Core.PublishedCache;
using Umbraco.Cms.Infrastructure.ModelsBuilder;
using Umbraco.Cms.Core;
using Umbraco.Extensions;

namespace Umbraco.Cms.Web.Common.PublishedModels
{
	// Mixin Content Type with alias "twThemeProperties"
	/// <summary>TW Theme Properties</summary>
	public partial interface ITwThemeProperties : IPublishedElement
	{
		/// <summary>Dark Mode Accent</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		bool DarkModeAccent { get; }

		/// <summary>Dark Mode Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		bool DarkModeBackground { get; }

		/// <summary>Dark Mode Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		bool DarkModeText { get; }

		/// <summary>Light Mode Accent</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		bool LightModeAccent { get; }

		/// <summary>Light Mode Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		bool LightModeBackground { get; }

		/// <summary>Light Mode Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		bool LightModeText { get; }

		/// <summary>Dark Mode Custom Accent Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TwDarkModeCustomAccentColor { get; }

		/// <summary>Dark Mode Custom Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TwDarkModeCustomBackgroundColor { get; }

		/// <summary>Dark Mode Custom Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TwDarkModeCustomTextColor { get; }

		/// <summary>Dark Mode Preset Accent Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetAccentColor { get; }

		/// <summary>Dark Mode Preset Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetBackgroundColor { get; }

		/// <summary>Dark Mode Preset Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetTextColor { get; }

		/// <summary>Light Mode Custom Accent Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TwLightModeCustomAccentColor { get; }

		/// <summary>Light Mode Custom Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TwLightModeCustomBackgroundColor { get; }

		/// <summary>Light Mode Custom Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		string TwLightModeCustomTextColor { get; }

		/// <summary>Light Mode Preset Accent Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetAccentColor { get; }

		/// <summary>Light Mode Preset Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetBackgroundColor { get; }

		/// <summary>Light Mode Preset Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetTextColor { get; }
	}

	/// <summary>TW Theme Properties</summary>
	[PublishedModel("twThemeProperties")]
	public partial class TwThemeProperties : PublishedElementModel, ITwThemeProperties
	{
		// helpers
#pragma warning disable 0109 // new is redundant
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const string ModelTypeAlias = "twThemeProperties";
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public new static IPublishedContentType GetModelContentType(IPublishedContentTypeCache contentTypeCache)
			=> PublishedModelUtility.GetModelContentType(contentTypeCache, ModelItemType, ModelTypeAlias);
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static IPublishedPropertyType GetModelPropertyType<TValue>(IPublishedContentTypeCache contentTypeCache, Expression<Func<TwThemeProperties, TValue>> selector)
			=> PublishedModelUtility.GetModelPropertyType(GetModelContentType(contentTypeCache), selector);
#pragma warning restore 0109

		private IPublishedValueFallback _publishedValueFallback;

		// ctor
		public TwThemeProperties(IPublishedElement content, IPublishedValueFallback publishedValueFallback)
			: base(content, publishedValueFallback)
		{
			_publishedValueFallback = publishedValueFallback;
		}

		// properties

		///<summary>
		/// Dark Mode Accent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("darkModeAccent")]
		public virtual bool DarkModeAccent => GetDarkModeAccent(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Accent</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static bool GetDarkModeAccent(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "darkModeAccent");

		///<summary>
		/// Dark Mode Background
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("darkModeBackground")]
		public virtual bool DarkModeBackground => GetDarkModeBackground(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static bool GetDarkModeBackground(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "darkModeBackground");

		///<summary>
		/// Dark Mode Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("darkModeText")]
		public virtual bool DarkModeText => GetDarkModeText(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static bool GetDarkModeText(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "darkModeText");

		///<summary>
		/// Light Mode Accent
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("lightModeAccent")]
		public virtual bool LightModeAccent => GetLightModeAccent(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Accent</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static bool GetLightModeAccent(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "lightModeAccent");

		///<summary>
		/// Light Mode Background
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("lightModeBackground")]
		public virtual bool LightModeBackground => GetLightModeBackground(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Background</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static bool GetLightModeBackground(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "lightModeBackground");

		///<summary>
		/// Light Mode Text
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[ImplementPropertyType("lightModeText")]
		public virtual bool LightModeText => GetLightModeText(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Text</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		public static bool GetLightModeText(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<bool>(publishedValueFallback, "lightModeText");

		///<summary>
		/// Dark Mode Custom Accent Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModeCustomAccentColor")]
		public virtual string TwDarkModeCustomAccentColor => GetTwDarkModeCustomAccentColor(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Custom Accent Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTwDarkModeCustomAccentColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "twDarkModeCustomAccentColor");

		///<summary>
		/// Dark Mode Custom Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModeCustomBackgroundColor")]
		public virtual string TwDarkModeCustomBackgroundColor => GetTwDarkModeCustomBackgroundColor(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Custom Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTwDarkModeCustomBackgroundColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "twDarkModeCustomBackgroundColor");

		///<summary>
		/// Dark Mode Custom Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModeCustomTextColor")]
		public virtual string TwDarkModeCustomTextColor => GetTwDarkModeCustomTextColor(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Custom Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTwDarkModeCustomTextColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "twDarkModeCustomTextColor");

		///<summary>
		/// Dark Mode Preset Accent Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModePresetAccentColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetAccentColor => GetTwDarkModePresetAccentColor(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Preset Accent Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetTwDarkModePresetAccentColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "twDarkModePresetAccentColor");

		///<summary>
		/// Dark Mode Preset Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModePresetBackgroundColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetBackgroundColor => GetTwDarkModePresetBackgroundColor(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Preset Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetTwDarkModePresetBackgroundColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "twDarkModePresetBackgroundColor");

		///<summary>
		/// Dark Mode Preset Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twDarkModePresetTextColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwDarkModePresetTextColor => GetTwDarkModePresetTextColor(this, _publishedValueFallback);

		/// <summary>Static getter for Dark Mode Preset Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetTwDarkModePresetTextColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "twDarkModePresetTextColor");

		///<summary>
		/// Light Mode Custom Accent Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModeCustomAccentColor")]
		public virtual string TwLightModeCustomAccentColor => GetTwLightModeCustomAccentColor(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Custom Accent Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTwLightModeCustomAccentColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "twLightModeCustomAccentColor");

		///<summary>
		/// Light Mode Custom Background Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModeCustomBackgroundColor")]
		public virtual string TwLightModeCustomBackgroundColor => GetTwLightModeCustomBackgroundColor(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Custom Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTwLightModeCustomBackgroundColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "twLightModeCustomBackgroundColor");

		///<summary>
		/// Light Mode Custom Text Color
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModeCustomTextColor")]
		public virtual string TwLightModeCustomTextColor => GetTwLightModeCustomTextColor(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Custom Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static string GetTwLightModeCustomTextColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<string>(publishedValueFallback, "twLightModeCustomTextColor");

		///<summary>
		/// Light Mode Preset Accent Color: Select the accent color from predefined colors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModePresetAccentColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetAccentColor => GetTwLightModePresetAccentColor(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Preset Accent Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetTwLightModePresetAccentColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "twLightModePresetAccentColor");

		///<summary>
		/// Light Mode Preset Background Color: Select the background color from predefined colors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModePresetBackgroundColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetBackgroundColor => GetTwLightModePresetBackgroundColor(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Preset Background Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetTwLightModePresetBackgroundColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "twLightModePresetBackgroundColor");

		///<summary>
		/// Light Mode Preset Text Color: Select the text color from predefined colors
		///</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[global::System.Diagnostics.CodeAnalysis.MaybeNull]
		[ImplementPropertyType("twLightModePresetTextColor")]
		public virtual global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor TwLightModePresetTextColor => GetTwLightModePresetTextColor(this, _publishedValueFallback);

		/// <summary>Static getter for Light Mode Preset Text Color</summary>
		[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Umbraco.ModelsBuilder.Embedded", "15.3.0+131c9cd")]
		[return: global::System.Diagnostics.CodeAnalysis.MaybeNull]
		public static global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor GetTwLightModePresetTextColor(ITwThemeProperties that, IPublishedValueFallback publishedValueFallback) => that.Value<global::Umbraco.Cms.Core.PropertyEditors.ValueConverters.ColorPickerValueConverter.PickedColor>(publishedValueFallback, "twLightModePresetTextColor");
	}
}
